version: "3.9"
services:
    front:
        build: ./front
        ports:
            - "8080:8080"
        networks:
            - default
    back:
        build: ./back
        ports:
            - "5000:5000"
        networks: 
            - default
networks: 
    default:
        external:
          name: enroll_network